//ERRORS
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//REGISTER
export const USER_REGISTERED_FOR_CONFIRMATION =
  "USER_REGISTERED_FOR_CONFIRMATION";
export const USER_CONFIRMED = "USER_CONFIRMED";
export const CHECK_USER_CONFIRMATION = "CHECK_USER_CONFIRMATION";
export const NEW_CONFRIMATION_MAIL = "NEW_CONFRIMATION_MAIL";
export const SEND_RESET_LINK = "SEND_RESET_LINK";
export const CHECK_RESET_TOKEN = "CHECK_RESET_TOKEN";
export const RESET_PASSWORD = "RESET_PASSWORD";

//AUTH
export const SET_CURRENT_USER = "SET_CURRENT_USER";
